### ISSUE TITLE
ZipArchive with file of unity

### ISSUE THREAD

**Issue by lrsalway-here** [ZipArchive/ZipArchive#525] opened 2019-08-08 08:44 UTC
I integrated the unity file with iOS native project, and the ZipArchive could not be used normally.
![no name](https://user-images.githubusercontent.com/18479815/62688586-bb312200-b9fb-11e9-9353-a205e3a5f0c2.png)

**Comment by Coeur** [comment] 2019-08-08 09:13
EXC_BAD_ACCESS sounds to me that you're not using the compiled files matching the displayed code: could be a cache issue from a different version. You should delete all your DerivedData while Xcode is closed, then open Xcode and build again.

**Comment by lrsalway-here** [comment] 2019-08-08 09:47
I see your location shows Shanghai. Can you speak Chinese？I will share the unity project with you tomorrow.thanks!

**Comment by Coeur** [comment] 2019-08-08 09:52
Sorry, I'm the only Shanghainese not speaking Chinese.

Other checks that you may try:
- you're on version 2.2.2
- did you install SSZipArchive through CocoaPods, Carthage, Git submodule, or some Nuget-for-Unity package that I've never heard about?
- could you try to replace `[self class]` with `SSZipArchive` in the code to see if it makes any difference?

**Comment by lrsalway-here** [comment] 2019-08-12 01:33
I put SSZipArchive directly into the project and integrated the unity project into the project based on the url below. SSZipArchive doesn't work. I tried debugging, but I couldn't solve the problem. Before we used the old version, which could not be compressed. I changed the new version, but I still can't use it, but the error is different.

**Comment by lrsalway-here** [comment] 2019-08-12 01:37
https://blog.csdn.net/qq_36498627/article/details/89520589

**Comment by Coeur** [comment] 2019-08-12 01:41
I don't understand where is the download button on this article.

**Comment by lrsalway-here** [comment] 2019-08-12 01:43
Can you read Chinese？

**Comment by Coeur** [comment] 2019-08-12 01:43
No I can't, sorry.

**Comment by lrsalway-here** [comment] 2019-08-12 01:51
If I give you a project, can you help me to debug it?

**Comment by Coeur** [comment] 2019-08-12 02:49
Yes, when I got some time for it (I'm super busy for the next two days for sure).

**Comment by lrsalway-here** [comment] 2019-08-12 03:03
Thx,I had already added you in WeChat.

**Comment by auqarius** [comment] 2019-09-21 11:03
Are u guys fixed this?? Totally same question with @lrsalway-here .

**Comment by auqarius** [comment] 2019-09-21 11:06
> Thx,I had already added you in WeChat.

Hi, pls let me know if u fixed this. 410592634 is my QQ, add me.

**Comment by auqarius** [comment] 2019-09-23 02:44
@Coeur Have you fixed this? We need to fix this crash ASAP, need help.

**Comment by jhudsonWA** [comment] 2019-09-23 03:00
Looking at the history, no test project was every supplied.

**Comment by auqarius** [comment] 2019-09-23 03:25
@jhudsonWA I'm trying to make a test project, I will post it on github when it finished. Can u help me to find this?

**Comment by jhudsonWA** [comment] 2019-09-23 03:59
@auqarius Post a test project and we can try. It's a balance, we can't spend all of our time supporting end users of the library, especially when other unrelated projects are involved, but we are curious if there is actually a bug in our library.

**Comment by auqarius** [comment] 2019-09-23 10:22
@jhudsonWA The unity file is too large, I upload it to Github all day but failed, can u leave a email and I will send project in a email. (Now situation in test project is do not crash anymore but unzip result wrong.)

**Comment by auqarius** [comment] 2019-09-23 10:35
Finally my colleague pushed success, https://github.com/ghosthk/UnityUnzipTest, u can download project from this page.

**Comment by jhudsonWA** [comment] 2019-09-23 13:17
I'll take a look at it today, but I worry about this statement: "Now situation in test project is do not crash anymore but unzip result wrong.", so your telling me your test project does not actually reproduce the issue you are having in your main project?

**Comment by auqarius** [comment] 2019-09-24 02:01
In my main project, this issue has always occurred, but when I make a test project, this issue disappears. I'm confused too... But for some reason, I'm not allowed to post main project out of company. So I post the test project first, and i will keep going to reproduce this issue and find what caused it. If you have some discovery, please let me know. BTW, I totally understand the balance you said, any clue will be helpful to me.

**Comment by lrsalway-here** [comment] 2019-11-13 03:27
@auqarius 没法加你qq啊

**Comment by lrsalway-here** [comment] 2019-11-13 04:07
@jhudsonWA 
<img width="995" alt="图片" src="https://user-images.githubusercontent.com/18479815/68732046-0ebf9700-060d-11ea-8394-653ec5634bed.png">

I put my project on Baidu Netdisk, Can you download it?
https://pan.baidu.com/s/1DGzpZq2nS2-IbihGzqKy4g  
password: a9bh 

Google Drive：
https://drive.google.com/open?id=1OcKi6HDVZb5raDq0fAnxa8P-MD5zZAL0

**Comment by vvgool** [comment] 2019-12-02 10:11
i meet the same question ? are you fixed it?unity2018.2.20 is running ok ,but unity2018.4 crash

**Comment by kiwipvt** [comment] 2019-12-28 17:44
I am also facing same issue. unity2018.2.20 is running ok ,but unity2018.4.11, unity2018.4.14, 2019.2.17 are crashing. Any insight or solution please

**Comment by kiwipvt** [comment] 2019-12-29 09:45
@vvgool @lrsalway-here did you find reason/cause and solution for same issue? Any help is appreciated.

**Comment by kiwipvt** [comment] 2020-01-14 10:26
I din't find reason of crash. But currently added workaround. Crash was happening because of stack corruption due to `unzGetCurrentFileInfo` function call. so i replaced `unz_file_info fileInfo;` with `unz_file_info64 file_info1;unz_file_info64 file_info2;unz_file_info fileInfo;` in SSZipArchive.m, so that stack corruption dont affect variable `directoriesModificationDates`

**Comment by willson-chen** [comment] 2020-04-27 07:33
@lrsalway-here @auqarius @vvgool Looks the same as this issue: #362

**Comment by willson-chen** [comment] 2020-05-15 03:09
The cause and solution of the problem exist in the discussion of #362，I will close this issue first.

**Closed by willson-chen** 2020-05-15 03:09 UTC
Labels: needs-reproduction
