### ISSUE TITLE
Special symbols in archive name

### ISSUE THREAD

**Issue by Lenok** [ZipArchive/ZipArchive#412] opened 2017-10-26 06:43 UTC
SSZipArchive on iOS can't unzip file with name which contains dashes(h5uo4n0v569s-earth-1508948742470.zip)

**Comment by Coeur** [comment] 2017-10-26 10:52
I assume you mean iOS 11, right?
I'll test it.

**Comment by Lenok** [comment] 2017-10-26 12:05
Yes, iOS 11.
Thank you.

**Comment by Coeur** [comment] 2017-10-30 05:43
No issue at all on a real iPhone 8.
I'll close the issue as I believe there is nothing wrong regarding handling dashes in filenames.

If you really find an issue, try to confirm the configuration that is causing issue. For instance, you can:
* either share a zip file that fails on simulator with one of the example projects (ObjectiveCExample or SwiftExample).
* either clone the project and alter one of the example projects (https://github.com/ZipArchive/ZipArchive/tree/master/ObjectiveCExample or https://github.com/ZipArchive/ZipArchive/tree/master/SwiftExample) to reproduce the issue
* either directly add a unit test that fails in https://github.com/ZipArchive/ZipArchive/blob/master/ObjectiveCExample/ObjectiveCExampleTests/SSZipArchiveTests.m
* either share your own project that has issues

Hope you'll identify the real cause of the issue.

**Comment by Lenok** [comment] 2017-11-03 06:52
Hello, this is changes for ObjectiveCExample ViewController.m for reproduction:

`
@property (copy, nonatomic) NSString *unzipPath;

@end

@implementation ViewController

#pragma mark - Life Cycle
- (void)viewDidLoad {
    [super viewDidLoad];
    
    _file1.text = @"";
    _file2.text = @"";
    _file3.text = @"";
    
    NSString* documentsPath = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES)[0];
    NSString* fileName = [NSString stringWithFormat:@"%@/%@", documentsPath,@"h5uo4n0v569s-earth-1508948742470.zip"];
    NSURL  *fileURL = [NSURL URLWithString:@"https://fndy-upload-s3-test.s3.amazonaws.com/h5uo4n0v569s-earth-1508948742470.zip"];
    
    
    NSData *urlData = [NSData dataWithContentsOfURL:fileURL];
    if(urlData)
    {
        [urlData writeToFile:fileName atomically:YES];
        NSString *unzipPath = [NSString stringWithFormat:@"%@/%@",
                               NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES)[0],@"h5uo4n0v569s-earth-1508948742470"];
        NSURL *url = [NSURL fileURLWithPath:unzipPath];
        
        [[NSFileManager defaultManager] createDirectoryAtURL:url
                                 withIntermediateDirectories:YES
                                                  attributes:nil
                                                       error:nil];
        _zipPath = fileName;
        _unzipPath = unzipPath;
        _unzipButton.enabled = YES;
    }
    
}`

`- (IBAction)unzipPressed:(id)sender {
    if (!_zipPath) {
        return;
    }
    if (!_unzipPath) {
        NSString *_unzipPath = [self tempUnzipPath];
        if (!_unzipPath) {
            return;
        }

    }
    NSString *password = _passwordField.text;
    BOOL success = [SSZipArchive unzipFileAtPath:_zipPath
                                   toDestination:_unzipPath
                              preserveAttributes:YES
                                       overwrite:YES
                                  nestedZipLevel:0
                                        password:password.length > 0 ? password : nil
                                           error:nil
                                        delegate:nil
                                 progressHandler:nil
                               completionHandler:nil];
...`

**Comment by Coeur** [comment] 2017-11-03 08:11
Thanks, I'll see if I can reproduce.

**Comment by willson-chen** [comment] 2020-01-10 07:52
@Lenok 
Hi,according to the link you provided: https://fndy-upload-s3-test.s3.amazonaws.com/h5uo4n0v569s-earth-1508948742470.zip, I downloaded the file on the Windows system and prompted "The archive is either in unknown format or damaged ”Download on macOS, also prompts inappropriate file types and formats.

On the macOS system, I removed the dashes and I also couldn't open the file. Then use ZipArchive to decompress and return -103 failed to open the file.


So I think the file cannot be decompressed because of file corruption. Not related to zip archive software.

**Comment by willson-chen** [comment] 2020-01-13 07:30
@Lenok 

I use some command tools to test this zip file, including `p7z`, `zip -T`, `minizip`. I am sure about that the unzip failure is caused by the file itself.

So I will close this issue. Any more question please append comment. :)

**Closed by willson-chen** 2020-01-13 07:30 UTC
Labels: needs-reproduction
