### ISSUE TITLE
unzip succeed, but some files was lost

### ISSUE THREAD

**Issue by evanycyc** [ZipArchive/ZipArchive#679] opened 2023-05-18 03:25 UTC
BOOL result = [SSZipArchive unzipFileAtPath:decPath toDestination:filePath];
result is YES, but some files don't exist in folder occasionally.

**Comment by arinjay** [comment] 2023-09-01 14:13
getting same issue , 
unzip success, but error in getting the contents

**Comment by Coeur** [comment] 2023-09-02 11:22
Which version of ZipArchive?
Any particularities related to those failures?
- special permissions on a file or folder?
- special characters in the name?
- filetype or filesize?

(without steps to reproduce the problem, we should normally close this issue)

**Comment by arinjay** [comment] 2023-09-04 05:43
version used: 2.4.3

- No special permission is required to unzip that file
- no unique character in the same
- Unzip file size ~ 4 MB

**Comment by Coeur** [comment] 2023-09-04 09:22
Then I'm afraid, but that's not enough out-of-the-ordinary to give any clue as to what happened.
If the issue is reproducible consistently:
- try with a newer version of ZipArchive to see if that resolves the issue
- try to share the archive here for analysis

We can't do more.

**Comment by stephent** [comment] 2023-10-03 00:35
I'm seeing the same with this file (remove `.txt` for original KMZ file):

[waterfall creek cutoff.kmz.txt](https://github.com/ZipArchive/ZipArchive/files/12787395/waterfall.creek.cutoff.kmz.txt)

File size: 4270 bytes
Unzipped: 96 bytes

```
BOOL result = [SSZipArchive unzipFileAtPath:kmzURL.path toDestination:unzipURL.path overwrite:YES password:nil error:&error];
```

Using v2.5.4 in Xcode 15 while debugging, `result` is `YES` and `error` is `nil`.

**Comment by Coeur** [comment] 2024-10-01 09:17
Tested on 2.5.5 and 2.6.0: I get a 15258 bytes file named doc.kml.
Closing.

**Closed by Coeur** 2024-10-01 09:17 UTC
Labels: bug
