### ISSUE TITLE
SSZipArchive skipping some files and folders in unarchiving

### ISSUE THREAD

**Issue by sameer4** [ZipArchive/ZipArchive#409] opened 2017-10-23 06:39 UTC
i'm trying to unarchive a zip file from SSZipArchive using 
`[SSZipArchive unzipFileAtPath:[self getDocumentPath:[NSString stringWithFormat:@"panorama_%@.zip",panoramaID]] toDestination: [self getDocumentPath:[NSString stringWithFormat:@"panorama_%@",panoramaID]]];`

but it skips a airbus_a320.xml file from parent folder and some jpg files and folder in sub folder.but works fine on same structure with different zip file

**Comment by Coeur** [comment] 2017-10-23 09:20
Can you share an archive that demonstrates the issue?
Can you confirm that you are using ZipArchive 2.1.1?

**Comment by sameer4** [comment] 2017-10-23 09:41
yes i'm using SSZipArchive 2.1.1.i also tried with SSZipArchive 2.1.0.same issue.
link to file:
https://www.dropbox.com/s/jn6w3nu9knghrbv/panorama_3.zip?dl=0

**Comment by Coeur** [comment] 2017-10-23 10:37
I have no problem fully unzipping the archive from simulator
<img width="432" alt="screen shot 2017-10-23 at 6 34 47 pm" src="https://user-images.githubusercontent.com/839992/31884820-05672f5a-b7b4-11e7-87c9-60f6b32d39d4.png">

You may want to double check the paths to what you're unzipping and where you're unzipping.

**Comment by sameer4** [comment] 2017-10-26 08:22
working fine now, made it extract on main thread.i should not be an issue but it solved the problem anyway.

**Comment by Coeur** [comment] 2017-10-26 10:51
Oh, I should try from a non-main Thread to see if that's an issue.

**Comment by Coeur** [comment] 2017-10-30 06:06
Thread is not an issue according to my tests. I get 2,278 items always.

My test was to use:

    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        BOOL success = [SSZipArchive unzipFileAtPath:_zipPath
                                       toDestination:unzipPath
                                  preserveAttributes:YES
                                           overwrite:YES
                                      nestedZipLevel:0
                                            password:password.length > 0 ? password : nil
                                               error:nil
                                            delegate:nil
                                     progressHandler:nil
                                   completionHandler:nil];
          // ...

So I'll close this as I can't reproduce it. If you feel it's still an issue, please fork either ObjectiveCExample or SwiftExample projects and modify it to demonstrate an issue.

**Closed by Coeur** 2017-10-30 06:06 UTC
Labels: needs-reproduction

**Comment by RushitaBacancy** [comment] 2023-02-24 11:05
When I try to zip any folder it becomes a .zip folder successfully. Now I unzip the folder and see that many files are missing.

I make a zip without password.
