### ISSUE TITLE
Compress the sandbox problem

### ISSUE THREAD

**Issue by xinyangslove** [ZipArchive/ZipArchive#435] opened 2018-01-03 09:54 UTC
Compressed ios sandbox file, and then overwrite the operation causes the program not to read sandbox file, more serious

**Comment by jhudsonWA** [comment] 2018-01-06 22:34
Can you give an example?

**Comment by jhudsonWA** [comment] 2018-01-16 06:17
Anything? Please respond or I will close this issue within 24 hours.

**Comment by xinyangslove** [comment] 2018-01-16 08:07
Found a problem, may not be caused by ZipArchive, the other is ZipArchive If coupled with the password decompression rate is very slow

**Comment by jhudsonWA** [comment] 2018-01-16 13:42
Details please: what environment, iOS version, ZipArchive version, etc. 

We test decompression with a password in our standard test suite and it is not slow.

**Comment by jhudsonWA** [comment] 2018-04-10 03:36
Any update on this?

**Comment by Coeur** [comment] 2018-04-10 04:00
He wrote "_may not be caused by ZipArchive_", so I wouldn't worry much. ;)

Maybe we close it for now, and we re-open it if we get a confirmation that it's caused by ZipArchive.

**Comment by jhudsonWA** [comment] 2018-04-10 04:03
Done and done. :)

**Closed by jhudsonWA** 2018-04-10 04:03 UTC
Labels: needs-reproduction, question
