### ISSUE TITLE
Use password compression problem

### ISSUE THREAD

**Issue by king129** [ZipArchive/ZipArchive#337] opened 2017-05-11 07:31 UTC
- use `createZipFileAtPath:withFilesAtPaths:withPassword` API, compressed file cannot be opened

**Comment by jhudsonWA** [comment] 2017-05-11 16:14
Cannot be opened where? Same device? On a mac? On windows? on android?

**Comment by king129** [comment] 2017-05-12 11:53
@jhudsonWA Mac windows, Android has not been tested

**Comment by jhudsonWA** [comment] 2017-05-12 17:40
Ok, we need to look into this a bit more then. You are not the first person who have said a password protected zip does not work cross platform.

**Comment by dillan** [comment] 2017-06-01 19:32
I am seeing a similar issue. Zip file is created on iOS, but cannot be unzipped on macOS.

```
user$ unzip /Users/user/Downloads/test.zip 
Archive:  /Users/user/Downloads/test.zip
   skipping: test/file1.txt  unsupported compression method 99
   skipping: test/file2.txt  unsupported compression method 99
   skipping: test/file3.txt  unsupported compression method 99
```

**Comment by monoqlo** [comment] 2017-06-27 00:41
Just for reference, `unzip` preinstalled in macOS don't support the compression method, but others (ex. [p7zip](http://p7zip.sourceforge.net), [The Unarchiver](https://itunes.apple.com/jp/app/the-unarchiver/id425424353?mt=12) ) do.

**Comment by Coeur** [comment] 2017-06-27 04:50
@monoqlo do we know what compression methods with password are supported by `/usr/bin/unzip`?

**Comment by Coeur** [comment] 2017-09-19 05:52
Closing as duplicate of #228

**Closed by Coeur** 2017-09-19 05:52 UTC
Labels: duplicate
