### ISSUE TITLE
SSZipArchive.createZipFile with password Archive Utility open error

### ISSUE THREAD

**Issue by liufsd** [ZipArchive/ZipArchive#303] opened 2016-12-16 08:33 UTC
let result = SSZipArchive.createZipFile(atPath: "/Users/liupeng/Desktop/result.zip", withContentsOfDirectory: "/Users/liupeng/Desktop/testfilesA/", keepParentDirectory: true, withPassword: "test")

But when i just open the result.zip, Archive Utility tips "error 1 - Operation not permitted.", but other app can open it and tips me to input password. 
So why system zip utils not work?

**Comment by Coeur** [comment] 2017-08-01 01:45
@BassMunkee @liufsd  Please try version 2.0.2 of SSZipArchive and give us a sample zip if that's still an issue. Note that there is a known issue if folder or file is empty.

**Comment by irenacher** [comment] 2017-08-02 19:25
I am using SSZipArchive version 2.0.3 installed from CocoaPods and still have this very issue with Archive Utility on Mac. RAR Lite is able to open it correctly after prompted for password.

**Comment by Coeur** [comment] 2017-08-03 04:51
@irenacher as wrote above, please provide a sample zip for us.

**Comment by Coeur** [comment] 2017-09-19 03:46
@liufsd @BassMunkee @irenacher closing for now, as lacking of information to reproduce the issue as stated above.

**Comment by Coeur** [comment] 2017-09-19 03:55
[#303 not unzippable with Archive Utlity password a.zip](https://github.com/ZipArchive/ZipArchive/files/1312996/303.not.unzippable.with.Archive.Utlity.password.a.zip)

Oh well, reproduced myself with the attached sample that was produced using ZipArchive 2.0.7.

**Comment by Coeur** [comment] 2017-09-19 05:04
OK, I figured this out:
SSZipArchive is using AES encryption by default, which is not supported by Archive Utility.
What we could do is to offer the choice of encryption (with or without AES).
Unfortunately, it is currently configurable at build time only (with C flag HAVE_AES).

**Comment by jhudsonWA** [comment] 2017-09-19 05:30
Ouch..

**Comment by Coeur** [comment] 2017-09-19 05:36
Possible compression methods that I can see for curfile64_info->method:
* Z_DEFLATED == 8
* Z_BZIP2ED == 12
* AES_METHOD == 99

I checked that keka is using Z_DEFLATED by default and that we are using AES_METHOD by default. I haven't tested Archive Utility for Z_BZIP2ED, but that could be interesting to know.

**Comment by Coeur** [comment] 2017-09-19 05:45
For chronological reasons, I'll close this issue as a duplicate of #228.

**Closed by Coeur** 2017-09-19 05:45 UTC
Labels: bug, feature

**Comment by designerfuzzi** [comment] 2023-12-25 04:20
still an issue.

console tells a more specific report:
`bomCopierFatalError:Couldn't read pkzip signature.`
and
`bomCopierFatalError:Not a central directory signature`

here a hex print of the generated zip.
`50 4B 03 04 2D 00 08 08 08 00 15 29 99 57 00 00 00 00 FF FF FF FF FF FF FF FF 16 00 14 00 2F 4F 63 74 6F 62 75 73 5F 5F 2F 62 61 6E 6B 31 30 2E 77 6F 72 6B 01 00 10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ED DD 4D 72 6C 47 5E`
and compare same contents as result of using Archive Utility to zip.
`50 4B 03 04 0A 00 00 00 00 00 15 29 99 57 00 00 00 00 00 00 00 00 00 00 00 00 0A 00 10 00 4F 63 74 6F 62 75 73 5F 5F 2F 55 58 0C 00 9F 01 89 65 4A 00 89 65 F5 01 14 00 50 4B 03 04 14 00 08 00 08 00 15 29 99 57 00 00 00 00 00 00 00 00 00 00 00 00 15 00 10 00 4F 63 74 6F 62 75 73 5F 5F 2F 62 61 6E 6B 31 30 2E 77 6F 72 6B 55 58 0C 00 4A 00 89 65 4A 00 89 65 F5 01 14 00 ED DD 4D 72 6C 47 5E`

so i can confirm the PKzip headers are fundamental different. I particular Apple places the directory in front, SSZipArchive not. Very likely same issue on all other apple platforms. 
Also suspicious AES seems not the problem but maybe not using does fix the signature sometime. 
Apart from that SSZipArchive can not be compiled without the compiler flag `HAVE_WZAES`, it will try to link functions that are not available. 
`

**Comment by Coeur** [comment] 2023-12-28 22:26
@designerfuzzi ES was made optional six years ago in https://github.com/ZipArchive/ZipArchive/pull/393.
Please open a new separate issue.
