### ISSUE TITLE
Crash in unzipFileAtPath: in Unity 2020

### ISSUE THREAD

**Issue by markyama** [ZipArchive/ZipArchive#605] opened 2021-01-29 19:21 UTC
When using SSZipArchive in Unity 2020.1.4.f1 (on iOS device), I am getting a crash as described in this post:
https://forum.unity.com/threads/ios-ssziparchive-unzip-file-of-unity-crash.787928/

The crash happens in unzipFileAtPath:toDestination:overwrite:password:error:

The crash always comes at the same point as shown by the screenshot by WiesenWang. I could not get the workaround by rbhushan working, although it does seem like the stack is being corrupted in unzGetCurrentFileInfo. I tried changing the var fileInfo to a unz_file_info64, and used unzGetCurrentFileInfo64 instead of unzGetCurrentFileInfo. This moved the crash down in the function, but it still did crash.

SSZipArchive is actually being used by Google’s MLKit DigitalInkRecognition cocoapod. I’m running SSZipArchive v2.2.3 with MLKitDigitalInkRecognition 1.1.0. 

When I run the google samples mlkit quickstart for digital ink recognition, the code works in the simulator and on a device. But when I install the pods on Unity and run on iOS device I get the crashing. I believe this is due to the memory pressure caused with my larger Unity app than the quickstart.

BTW, when I tried unzipping the same zip files in my Unity app using a different unzipping util, it succeeded.

### Steps to reproduce
-Added pod MLKitDigitalInkRecognition (1.1.0) to my unity project
-Added bridge code to make calls to MLKit from my Unity project
-After MLKit downloads a recognition model, to my device. The first time you try to recognize ink using that model, MLKit calls SSZipArchive’s unzipFileAtPath:toDestination:overwrite:password:error: to unzip some of the downloaded files.
It crashes in the same place as shown in:
https://forum.unity.com/threads/ios-ssziparchive-unzip-file-of-unity-crash.787928/

### Expected behavior
-Not to crash on unzip

### Version of ZipArchive
SSZipArchive v2.2.3

### Environmental information
iPhone 6s plus running 14.3
iPhone 7 plus running 14.1
Built using 2020.1.4.f1

Thanks for any help.

**Comment by Coeur** [comment] 2024-11-10 15:54
Duplicate of #602.

**Closed by Coeur** 2024-11-10 15:54 UTC
Labels: Unity

**Comment by Coeur** [comment] 2024-11-10 17:32
>pod 'MLKitDigitalInkRecognition'

That should install SSZipArchive 2.6.0 nowadays, instead of your SSZipArchive 2.2.3 at the time, so it's probably good (no other crash report than you in past 3 years).

**Comment by Coeur** [comment] 2024-11-10 18:39
Also duplicate of https://github.com/ZipArchive/ZipArchive/issues/362:
You were maybe using two incompatible versions of minizip together.
