### ISSUE TITLE
After compressing the Unix executable file, Use the system decompression,  it will become a normal file

### ISSUE THREAD

**Issue by Shellylang** [ZipArchive/ZipArchive#657] opened 2022-10-21 06:22 UTC
### Steps to reproduce
1. SSZipArchive.createZipFile("zip path", "executable file path")

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

check posixPermissions 775 became 644

### Version of ZipArchive
SSZipArchive 2.4.2

### Environmental information
macos 12.0

**Comment by Coeur** [comment] 2024-09-16 19:15
Analysis done in #689.
Fix in #716.

I'll close it as duplicate of #689, even if your issue is older. But thanks for reporting it.

**Closed by Coeur** 2024-09-16 19:15 UTC
