### ISSUE TITLE
Unable to import and use in Xcode 10.2 Swift 4 by manually drag and drop. Lot's of semantic issue errors

### ISSUE THREAD

**Issue by Jagan32541** [ZipArchive/ZipArchive#527] opened 2019-08-13 12:59 UTC
I created Fresh new Xcode iOS project and followed below steps.

1. Drag & Drop SSZipArchive folder in Xcode project.
2. Created Briging Header and imported Header file I.e. #Import "SSZipArchive.h"
3. Added libz.tbd and security framework to a target linked frameworks and libraries.

Then after it gave lot's of semantic issues. Can somebody please help me on this. It Would be really helpful if there is a video of importing this files in XCode iOS project. Please help me.

**Comment by Jagan32541** [comment] 2019-08-13 13:18
@Coeur Please help me on importing manually in Xcode 10.2 and swift 4

**Comment by Coeur** [comment] 2019-08-13 13:20
Steps are at https://github.com/ZipArchive/ZipArchive#manual
Did you forgot libiconv?
What is the error?

**Comment by Jagan32541** [comment] 2019-08-13 13:36
Yes, I added  libz.tbd, libiconv and Security framework but the last step(below) i'm not aware where to keep below 
4. Add the following GCC_PREPROCESSOR_DEFINITIONS: HAVE_INTTYPES_H HAVE_PKCRYPT HAVE_STDINT_H HAVE_WZAES HAVE_ZLIB MZ_ZIP_NO_SIGNING $(inherited). .


For reference Please watch the video and suggest what i'm doing wrong .

https://drive.google.com/open?id=19XZHYo99H44EDqjLMoAGLHJ2mtfgO3nM

**Comment by Coeur** [comment] 2019-08-14 01:11
I'm in China, no access to Google Drive, sorry.
And if you don't know how to manually configure a project, why choosing the manual installation? Probably better to choose a Carthage installation for your needs.

Closing as duplicate of #526

**Closed by Coeur** 2019-08-14 01:11 UTC
Labels: needs-reproduction

**Comment by Jagan32541** [comment] 2019-08-14 05:21
Now it's working, I imported all classes instead of folders and removed minizip folder reference in some classes and  added GCC_PREPROCESSOR_DEFINITIONS is well.

Issue are coming with the folders. Thanks it's working.

**Comment by Coeur** [comment] 2019-08-14 06:20
> Now it's working, I [...] removed minizip folder reference in some classes

Some references are incorrect or superfluous?
Maybe worth a pull request if you found an issue.
