### ISSUE TITLE
Static library problem

### ISSUE THREAD

**Issue by liuteng000** [ZipArchive/ZipArchive#491] opened 2019-01-04 08:34 UTC
I build it to a static library, when I use it in my unity project with xCode10.1
There is a problem.  
xxx(15656,0x1a1e3f000) malloc: *** error for object 0x134330002: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
<img width="1375" alt="zip000" src="https://user-images.githubusercontent.com/13810922/50679331-9f2e5380-0fc8-11e9-80d2-19f67331e1b5.png">
<img width="835" alt="zip111" src="https://user-images.githubusercontent.com/13810922/50679355-b705d780-0fc8-11e9-95d9-c93d7899f5e4.png">

**Comment by liuteng000** [comment] 2019-01-04 08:35
<img width="1731" alt="zip222" src="https://user-images.githubusercontent.com/13810922/50679525-6347be00-0fc9-11e9-8373-09e24676799f.png">

**Comment by nmoinvaz** [comment] 2019-01-04 18:58
I believe this is a duplicate of https://github.com/ZipArchive/ZipArchive/issues/464.

**Comment by Coeur** [comment] 2019-04-28 07:01
@liuteng000, Please follow the linked issue given by nmoinvaz above. It's unlikely that you're using our latest release of ZipArchive, so I'll close the issue as lacking reproducibility.

**Closed by Coeur** 2019-04-28 07:01 UTC
