### ISSUE TITLE
Non-public API usage

### ISSUE THREAD

**Issue by mafaming** [ZipArchive/ZipArchive#513] opened 2019-05-14 11:05 UTC
![image](https://user-images.githubusercontent.com/11641379/57693037-d4d00100-767a-11e9-93c4-aa652efdb67e.png)

I saw someone raised this question, but did not see how to solve it, the problem has been closed, so I submitted this question, how to solve it?

**Comment by Coeur** [comment] 2019-05-14 11:45
The question is: how to reproduce your issue?
I've been using SSZipArchive in many apps for years. Maybe a hundred Apple reviews using SSZipArchive, and I never got that rejection.

Please specify your integration steps (CocoaPods, Carthage, Manual), the version of ZipArchive, and ideally provide a sample project (but I understand that in the case of AppStore review, you can hardly share it all).

It's also possible that another third-party is secretly using a different version of ZipArchive internally.

**Comment by cj1024** [comment] 2019-05-14 14:24
I checked my project and I believe that _canPerformAction: is caused by Flipboard's FLEX.
So I dropped FLEX and (maybe unnecessary) use ZipArchive instead of SSZipArchive.
Finally that works.





Obviously it's a mistake made by ITC.

**Comment by Coeur** [comment] 2019-05-15 00:41
@cj1024 what is ITC?
But true, Flipboard's FLEX would definitely be rejected by Apple review.

**Comment by cj1024** [comment] 2019-05-15 01:18
> @cj1024 what is ITC?
> But true, https://github.com/Flipboard/FLEX would definitely be rejected by Apple review. That's why they even recommend to set it as `pod 'FLEX', '~> 2.0', :configurations => ['Debug']` in your Podfile.

ItunesConnect

**Comment by cj1024** [comment] 2019-05-15 01:23
> @cj1024 what is ITC?
> But true, https://github.com/Flipboard/FLEX would definitely be rejected by Apple review. That's why they even recommend to set it as `pod 'FLEX', '~> 2.0', :configurations => ['Debug']` in your Podfile.

My App has been embeded with FLEX for years and it's the first rejection caused by this.

**Comment by Coeur** [comment] 2019-05-15 02:33
> My App has been embedded with FLEX for years and it's the first rejection caused by this.

Yeah, and in their source code, they wrote:
>https://github.com/Flipboard/FLEX/blob/ed49a4fc89281608f41bebd3d09b8e0e1f2ea4c8/Classes/ExplorerInterface/FLEXWindow.m#L52
>// Done at runtime with an obfuscated selector because it is private API. But you shoudn't ship this to the App Store anyways...

Meaning that they are knowingly trying their best to do something illegal without being caught. Well, it's out of scope here, so I'll close that issue for now.

**Closed by Coeur** 2019-05-15 02:33 UTC
Labels: needs-reproduction

**Comment by mafaming** [comment] 2019-05-15 03:45
I removed FLEX, now the review passed, thank you guys
