### ISSUE TITLE
UnzipFile API crashes on free(ioposix->filename);

### ISSUE THREAD

**Issue by sandsuma** [ZipArchive/ZipArchive#464] opened 2018-07-26 09:34 UTC
We were using [ziparchive](https://code.google.com/archive/p/ziparchive/ )  framework code from many years for unzipping operation in our iOS code.
I tried to upgrade to SSZiparchive, and my unzipping code started crashing.
Its crashing in `fclose_file_func` where it tries to close the file `fclose(ioposix->file)`.
The same piece of code is working fine with ziparchive, then I found `fclose_file_func` has just one line ` int ret;
    ret = fclose((FILE *)stream);
    return ret;`
compared to SSZiparchive .
In my case while unzipping it fails  somewhere in `unzOpen2` and trying to call `fclose_file_func` twice and complains for SIG ABRT.
Check the screenshot below for the issue.
![image](https://user-images.githubusercontent.com/18698558/43254230-9074b6c6-90e4-11e8-80ad-6f4887186bc6.png)

![image](https://user-images.githubusercontent.com/18698558/43254252-a00f04a6-90e4-11e8-81fb-48e4d35379a1.png)
I wanted to migrate to SSZiparchive to consume [zipperdown fix]

My zippath and destination paths are as below

/Users/sandhya/Library/Developer/CoreSimulator/Devices/1D841CCD-A36F-49AF-848A-33CE0512774B/data/Containers/Data/Application/414C18C7-DAD8-48AC-99C9-65179B7B54AF/tmp/resources.zip
Printing description of tempWWWDirectory:
/Users/sandhya/Library/Developer/CoreSimulator/Devices/1D841CCD-A36F-49AF-848A-33CE0512774B/data/Containers/Data/Application/414C18C7-DAD8-48AC-99C9-65179B7B54AF/tmp/wwwtemp

I want to migrate to SSZiparchive to consume zipperdown fix.
(https://github.com/ZipArchive/ZipArchive/pull/456) which is not available to older ziparchive.

**Comment by Coeur** [comment] 2018-08-26 06:43
Could you provide a zip file and/or a project that will reproduce the issue?

**Comment by Coeur** [comment] 2018-08-26 06:53
For reference, fclose_file_func has been like that for more than 6 years: it was changed on Github by minizip author with commit https://github.com/nmoinvaz/minizip/commit/6d35b6b8845fae3d3cbde67bdad40e47e4623cf8, and looking at the diff it seems that the change was technically made even earlier, possibly on 12 Feb 2005, by Zoran Stevanovic, as "Fix possible memory leak". So we're talking about code that has been in use without issue for 13 years now.

**Comment by nmoinvaz** [comment] 2018-08-26 16:08
Perhaps fclose_file_func is getting called twice? Maybe it should be:

```
if (ioposix->filename != NULL)
{
    free(ioposix->filename);
    ioposix->filename = NULL;
}
```

**Comment by Coeur** [comment] 2018-08-26 17:01
@nmoinvaz

You're correct on the possibility of a double call.
You're incorrect on the fix: even like that, `free(ioposix);` two lines below would get called twice, and that can't be prevented.

**Comment by Coeur** [comment] 2018-08-26 17:10
Looking closely:
1. fclose_file_func is only assigned to zclose_file
2. zclose_file is only used in fclose_buf_func
3. fclose_buf_func will free streamio

So it's unlikely that the problem is with current minizip code. @sandsuma, how did you integrate SSZipArchive (CocoaPods, Carthage, manually) and which version of it?

**Comment by sandsuma** [comment] 2018-08-27 07:26
@Coeur I cloned and downloaded the SSZiparchive project . Its embedded in my project. I cant share the my whole project But will see if I can recreate with the objective C sample you shared.

**Comment by Coeur** [comment] 2018-08-27 09:39
Please double check that you've correctly replaced all the minizip files, especially ioapi files.

**Comment by hjf325802** [comment] 2018-09-19 07:01
I have the same issue.
The reason is that SSZiparchive uses the MiniZip, and a third party lib (MailCore2 lib in my project) uses the MiniZip too.
My solution is to modify methods (unzOpenCurrentFilePassword 、 unzOpenCurrentFile3 ------> 
prefix_unzOpenCurrentFilePassword、  prefix_unzOpenCurrentFile3).

**Comment by Coeur** [comment] 2018-09-19 16:18
@hjf325802 Thank you for the insight. You may want to contact MailCore2 on the matter. Or attempt to build the pod as a static library and/or raise the issue at https://github.com/cocoapods/cocoapods/issues. But I recall that they may just advice to contact the vendor to prefix the dependencies: https://github.com/CocoaPods/CocoaPods/issues/6835

**Comment by Coeur** [comment] 2018-10-30 10:39
@hjf325802, I decided to investigate this issue, and...
* pod 'mailcore2-ios' shows no compatibility problem at all (no crash with ZipArchive)
* pod 'mailcore2-osx' alone can't build:
>ld: library not found for -lcrypto

According to StackOverflow, it's because MailCore2 on macOS requires OpenSSL:
https://stackoverflow.com/questions/20624584/library-not-found-for-lcrypto
https://stackoverflow.com/questions/40004099/xcode-8-and-ld-library-not-found-for-lcrypto

So it really sounds like a duplicate of https://github.com/CocoaPods/CocoaPods/issues/6835.
On top of that, [Apple says](https://developer.apple.com/library/mac/documentation/security/Conceptual/cryptoservices/GeneralPurposeCrypto/GeneralPurposeCrypto.html):
> "Although OpenSSL is commonly used in the open source community, OpenSSL does not provide a stable API from version to version. For this reason, although OS X provides OpenSSL libraries, the OpenSSL libraries in OS X are deprecated, and OpenSSL has never been provided as part of iOS."

So I had to use [`pod 'OpenSSL-Universal'`](https://github.com/krzyzanowskim/OpenSSL) to simply build mailcore2 for macos. And there were no crash with ZipArchive: https://github.com/ZipArchive/ZipArchive/tree/%23464.MailCore2

As sandsuma report was for iOS, and hjf325802 didn't specify if they were using an OpenSSL dependency, I'll close the issue as lacking reproducibility.

**Closed by Coeur** 2018-10-30 10:39 UTC
Labels: Minizip, needs-reproduction

**Comment by yiiim** [comment] 2019-01-23 06:33
这个是minizip版本问题,我已经得到解决了,下载最新版本的minizip代码替换掉即可.如果静态库不是你自己制作的可以尝试ar命令分离出静态库中的minizip的.o

**Comment by eenapol** [comment] 2019-04-18 02:12
> 这个是minizip版本问题,我已经得到解决了,下载最新版本的minizip代码替换掉即可.如果静态库不是你自己制作的可以尝试ar命令分离出静态库中的minizip的.o

Where did you download it？

**Comment by yiiim** [comment] 2019-04-18 03:52
> > 这个是minizip版本问题,我已经得到解决了,下载最新版本的minizip代码替换掉即可.如果静态库不是你自己制作的可以尝试ar命令分离出静态库中的minizip的.o
> 
> Where did you download it？

If I remember correctly, this is the repository, the author has fixed it, and the version you are using is too old.
