### ISSUE TITLE
Large OSX Zip Archives (>4 GB) did not work

### ISSUE THREAD

**Issue by 0x68** [ZipArchive/ZipArchive#36] opened 2013-01-13 21:36 UTC
I have noticed, that large Zip Archives (>4 GB) which are created with OSX are not working with minizip.
I think it depends on some Meta Files which are created on the Compressing process.
Is it possible to clean the Archives before unzipping the Archives ?
It is also silly that some __MACOSX directorys are created in the Documents Directory.

**Comment by Coeur** [comment] 2017-10-09 09:40
Interesting. Let's reopen this.

**Comment by jdeepwell** [comment] 2017-10-10 08:32
Could this issue already bite with a ZIP size of about 1GB?
The ZIP in question contains about 300,000 files (Cocoa Documentation) and when extracting it via [SSZipArchive unzipFileAtPath...] it only creates about 30,000 or so.

**Comment by Coeur** [comment] 2017-10-10 08:45
@jdeepwell can you link to the sample?

**Comment by jdeepwell** [comment] 2017-10-10 09:09
I uploaded the ZIP to: http://deepwell.name/Apple_API_Reference.docset.zip

I extracted this with (under macOS):
```
    NSString *zipPath = @"/Path/to/zipfile/Apple_API_Reference.docset.zip";
    NSString *destinationPath = @"/Path/to/place/of/extraction";
    [SSZipArchive unzipFileAtPath:zipPath toDestination:destinationPath overwrite:YES password:nil progressHandler:^(NSString *entry, unz_file_info zipInfo, long entryNumber, long total) {
        NSLog(@"%@", entry);
    } completionHandler:^ (NSString *path, BOOL succeeded, NSError * _Nullable complError){
        if (complError) NSLog(@"Error occured: %@", complError);
    }];
```

To check e.g. search for the file `hc8z3wx_vy.html` under `Apple_API_Reference.docset/Contents/Resources/Documents` in the extracted files. It's there in the ZIP and also when I extract that ZIP via command line unzip or Finder but not in the stuff extracted via SSZipArchive.

**Comment by Coeur** [comment] 2017-10-10 10:03
I confirm there is an issue.
Unzipping with ZipArchive is interrupted at 165,698,821 bytes instead of expected 2,129,626,642 bytes.

I got a Z_BUF_ERROR on unzipping `Apple_API_Reference.docset/Contents/Resources/Documents/ccassetslibrary.html.dashtoc` which is normally just a 1,209 bytes file.

**Comment by Coeur** [comment] 2017-10-10 11:50
We have a buffer size of 4096 and extraction fails at 158.0 MB uncompressed.
MiniUnz has a buffer size of 8192 and extraction fails at 298.6 MB uncompressed.

Could it mean that we don't support well archives larger than 100 MB?

**Comment by jhudsonWA** [comment] 2017-10-10 19:38
Should we revert this change? I would think large files would be a more common case than ones with invalid headers.

**Comment by Coeur** [comment] 2017-10-11 01:11
Let's not revert yet: with or without the Incorrect Headers fix, we're still unable to correctly unzip this file.

**Comment by Coeur** [comment] 2017-10-11 05:58
I'm trying to see if we had this working in the past, but sadly even ZipArchive 0.3.2 had the bug.

**Comment by Coeur** [comment] 2017-10-11 08:54
So, I've found the cause and a workaround... it's another kind of corrupted headers, this time regarding the number of files in the archive (more than 65535). And there is a second issue, my previous fix on Incorrect Headers is indeed interfering.

So first step, yes, @jhudsonWA , let's revert my previous fix :(

As for my workaround on the incorrect number of entries, it is sadly incompatible with "progress" of unzipping, as it will not report the correct total of files. So I'm trying to improve it before making a pull request.

**Comment by Coeur** [comment] 2017-10-11 10:24
OK, I got a fix compatible with "progress": I just recount all the files when opening the archive. https://github.com/nmoinvaz/minizip/pull/186

**Comment by jdeepwell** [comment] 2017-10-11 15:13
Great news @Coeur !
I'd be happy to give it a try once committed.

**Comment by Coeur** [comment] 2017-10-11 15:44
In a few minutes/hours, I'll make a hotfix release.

**Comment by jdeepwell** [comment] 2017-10-12 13:55
@Coeur I pulled just your changes to unzip.c/h and tried it with my ZIP archive. Worked like a charm! All 262666 files were extracted and a diff with the original files (after running it in the iOS Simulator) also turned out OK.

Well done and __many__ thanks!

PS: By the way the whole point of my unzipping was to get the Cocoa API docs over to Dash-iOS. iTunes currently refuses to transfer the docset with all its files to a device but transferring one ZIP archive of it works. So I added the SSZipArchive to the open source Dash-iOS code to unzip on the device - and it works now :)

**Comment by 0x68** [comment] 2017-10-25 08:31
Finally  :+1:

**Comment by Coeur** [comment] 2017-10-25 08:36
@0x68 I only ignored * __MACOSX*, I didn't work on 4 GB compatibility. :)

**Comment by Coeur** [comment] 2017-10-30 04:25
I've reformulated the requirements to specifically support Archive Utility undocumented compression method for files larger than 4 GB in #417.

Supporting large files in general (Zip64 format) is already implemented, so I'm closing this issue.

**Closed by Coeur** 2017-10-30 04:25 UTC
Labels: feature, help wanted

**Comment by 78developer** [comment] 2019-01-12 07:55
hi i am not compressing >1gb file compressing

**Comment by Coeur** [comment] 2019-04-28 09:57
@78developer please open a separate issue, with a reproducible case.
