### ISSUE TITLE
unpack encoding problem in windows

### ISSUE THREAD

**Issue by fangjunjie** [ZipArchive/ZipArchive#269] opened 2016-08-02 04:44 UTC
Compressed package can be unpacked in mac，while can not be unpack in windows
It is estimated that caused by the file encoding problem.
Is there any solution to this? 
Thank you very much

**Comment by fangjunjie** [comment] 2016-08-02 04:44
Compressed package can be unpacked in mac，while can not be unpack in windows
It is estimated that caused by the file encoding problem.
Is there any solution to this? 
Thank you very much

**Comment by CatPolice** [comment] 2016-08-10 02:38
The same problem

**Comment by jhudsonWA** [comment] 2016-08-10 20:06
Checked in and tested. Creating a release now. I think I'll use your sample zip to add a test to make sure this support remains in future releases.

**Comment by wwwang89** [comment] 2017-08-01 13:01
IS It support Chinese name now ？when I use version 1.8.1，it cannot support，I'm so depressed！when I changed my file name to "test.zip"，It Can worked ！

**Comment by wwwang89** [comment] 2017-08-01 13:07
In the version 1.8.1，
there exists  the code：
// Check if it contains directory
            //            NSString * strPath = @(filename);
            NSString * strPath = [NSString stringWithCString:filename encoding:NSUTF8StringEncoding];
            //if filename contains chinese dir transform Encoding
            if (!strPath) {
                NSStringEncoding enc = CFStringConvertEncodingToNSStringEncoding(kCFStringEncodingGB_18030_2000);
                strPath = [NSString  stringWithCString:filename encoding:enc];
            }
            //end by skyfox

but there no use ，when my zip file name is "压缩包测试.zip",It cannot unpack，when I changed my file name to "test.zip"，It Can worked ！is there something wrong ？

**Comment by jhudsonWA** [comment] 2017-08-01 14:12
Please try with latest: 2.0.2. And if problem still exists upload test zip file.

**Comment by Coeur** [comment] 2017-08-02 01:43
@jhudsonWA wwwang is right, there is something weird happening at line https://github.com/ZipArchive/ZipArchive/blob/master/SSZipArchive/SSZipArchive.m#L332 why do we have a manual encoding specific workaround for Chinese only?

**Comment by Coeur** [comment] 2017-08-02 01:45
The weird code was done by #273

**Comment by Coeur** [comment] 2017-08-02 02:22
Also #334 and #315 may be linked. I'll assign myself to encoding issues.

**Comment by jhudsonWA** [comment] 2017-08-02 02:35
Thanks. I don’t remember the details of that check in. We probably should add some tests to verify encoding once resolved so we know we won’t have a regression again.

**Comment by Coeur** [comment] 2017-09-19 07:50
Marking as bug because of the weird piece of code we have.

**Comment by Coeur** [comment] 2017-09-28 02:45
Documentation on potential lists of encodings we may need to detect:
* https://pypi.python.org/pypi/chardet
* https://www.gnu.org/software/libiconv/
* https://developer.apple.com/documentation/corefoundation/cfstring/external_string_encodings

**Comment by Coeur** [comment] 2017-09-28 04:47
I've started to attempt to use encoding detection at https://github.com/ZipArchive/ZipArchive/tree/encoding_autodetection

But it's not ready yet, needs a bit more work.

**Closed** 2017-09-29 17:44 UTC
Labels: bug

**Comment by jsutdolph** [comment] 2019-01-28 10:40
I am getting problems with filename character encoding. The filename "17 What I’ve Been Looking For.pdf" is changed after a round-trip through SSZipArchive into: "17 What I‚Äôve Been Looking For.pdf".
The ’ character is actually composed of 3 bytes E2 80 99.
If I change the last argument to zipOpenNewFileInZip5() in SSZipArchive.m from 0 to (19<<8) (ie version madeby for OSX) it seems to correct the problem.
Can anybody have a comment about this?
Thanks
James Sutton

**Comment by Coeur** [comment] 2019-04-29 07:21
@jsutdolph I copied your comment in a new issue: #507
