### ISSUE TITLE
Password not recognized - should backwards compatibility for pre-AES files created with ZipArchive be built in?

### ISSUE THREAD

**Issue by inPhilly** [ZipArchive/ZipArchive#431] opened 2017-12-02 06:25 UTC
I have a file created with an app using ZipArchive in 2013. I have the correct password, but I am using SSZipArchive in an app trying to unzip that file, and it is saying that the password is wrong. I am certain that the passcode is correct as I have the code that produced the file with the passcode. Have you ever heard of an issue like this before?

**Comment by jhudsonWA** [comment] 2017-12-02 16:42
My guess is that the archive was created before AES encryption support landed. Now when it tries to apply the password it is doing so using AES which would make it not match. We were looking into a way to allow you to turn off AES support programmatically, but right now that is not possible. The passwords from before were just standard zip password though so any unzipping program should be able to open it

**Comment by inPhilly** [comment] 2017-12-02 20:26
I'm building via Carthage using objective-c. can't seem to find that file...

**Comment by inPhilly** [comment] 2017-12-02 20:28
I only need this to unzip those old files. Shouldn't that flag be available in the header files available for Carthage installs?

**Comment by inPhilly** [comment] 2017-12-02 20:38
Okay - I replaced with a manual install and did as you said. now it is saying that the password is correct, but the unzip still fails without a reason. Any more thoughts (and thanks for your help by the way).

**Comment by inPhilly** [comment] 2017-12-02 20:49
Sooo, I went back to the old version, when the app was shipped, before AES. That worked. Thank you!

**Comment by inPhilly** [comment] 2017-12-02 21:04
Still, it does seem odd that backwards compatibility was not built is... am I wrong?

**Comment by jhudsonWA** [comment] 2017-12-02 22:40
It should be... Would you be willing to share the zip file? Or is that not possible?

**Comment by inPhilly** [comment] 2017-12-03 05:33
I'm sorry - I wish I could. The file has data that might be sensitive and even so, I can't share the password.

**Comment by inPhilly** [comment] 2017-12-03 05:35
I do want to help you though. The old code gives so many warnings in Xcode and I don't know how to dix fix them haha! In any case, I always want to try to help a fellow programmer. I am trying to think of how I can help.

**Comment by jhudsonWA** [comment] 2017-12-03 05:40
Can you password protect just a text file using the old version, with a password like password and then try it in latest version to see if it has the same issue?

**Comment by jhudsonWA** [comment] 2017-12-03 05:41
That would give us a test file that is not sensitive.

**Comment by inPhilly** [comment] 2017-12-03 05:46
No, it is not that kind of an app. I wish I could. I can tell you which version of ZipArchive I used to create the file though.

**Comment by inPhilly** [comment] 2017-12-03 05:47
//  ZipArchive.m
//  
//
//  Created by aish on 08-9-11.
//  acsolu@gmail.com
//  Copyright 2008  Inc. All rights reserved.

**Comment by inPhilly** [comment] 2017-12-03 05:47
Does that help at all?

**Comment by jhudsonWA** [comment] 2017-12-03 05:55
Probably not without a version number of some sort. Oh well, glad you got your data decrypted. I'm going to close and reopen in the future if it comes up again.

**Comment by inPhilly** [comment] 2017-12-03 06:13
I can cut and paste the files if that would help.

**Comment by inPhilly** [comment] 2017-12-03 06:15
That didn't work. If you have a Dropbox link or somewhere I can upload to, I can give you all the files. There aren't too many - 9.

**Comment by jhudsonWA** [comment] 2017-12-03 06:42
Let me know when uploaded and I'll remove link: https://www.dropbox.com/sh/hsg592omf2bs540/AAB0KETFV5NZqB-4rFL9xgjMa?dl=0

**Comment by inPhilly** [comment] 2017-12-03 06:58
I don't think it is letting me upload, only download.

**Comment by inPhilly** [comment] 2017-12-03 06:59
My Dropbox is completely full or else I'd put it there.

**Comment by inPhilly** [comment] 2017-12-03 07:00
2 Gigs goes fast.

**Comment by jhudsonWA** [comment] 2017-12-03 07:05
Try this one: https://www.dropbox.com/request/no64JEO7B75bDJ8fwZlA

**Comment by inPhilly** [comment] 2017-12-03 07:08
Done.

**Comment by jhudsonWA** [comment] 2017-12-03 12:22
Thanks!

**Comment by inPhilly** [comment] 2017-12-06 02:10
Any updates?

**Comment by inPhilly** [comment] 2018-01-18 14:54
Any more thoughts on possibly updating this? I am now having to use the old version and it is causing so many warnings in my app (I don't know how to make these errors go away because I don't know this language). I understand that this is low priority, but in my apps, I try to take care of people all the way back to the first version in terms of making sure the app is operable. If I don't want to render my user's older backup files unusable, I have to use this bug-filled version.  : (

**Comment by inPhilly** [comment] 2018-02-15 22:57
Any ideas on another library I could use that would handle the old files properly and will compile without multiple errors?

**Comment by jhudsonWA** [comment] 2018-02-15 23:47
What language is your app written in? 

There are several other iOS unzipping libraries here on Github. You would just need to find one that supports password protected unzips without AES.

I don't know what kind of app you made, but without a test file, it's really hard to test compatibility.  Do you not have a way to create a backup with test data that shows the problem?

**Comment by Coeur** [comment] 2018-04-09 09:28
@inPhilly Hi, and sorry for the late response. Normally, we never meant to broke decompression of anything. Please provide me a sample zip file (and it's password) that doesn't uncompress anymore, and I'll look into what is causing the issue.

**Comment by jhudsonWA** [comment] 2018-04-10 03:36
@Coeur I did ask for a simple project and due to the type of zip files @inPhilly's app creates I have not been able to get one yet. Hopefully they can supply a test file and we can get this one figured out.

**Comment by Coeur** [comment] 2024-11-11 08:19
Our unit tests ensure we support both AES decryption (testUnzippingWithAESPassword) and PKWARE decryption (testUnzippingWithPassword).

Closing, in the absence of reproduction steps.
I can re-open if you provide a sample archive with the issue.

**Closed by Coeur** 2024-11-11 08:19 UTC
Labels: question, needs-reproduction
