### ISSUE TITLE
Unzipping multiple folders

### ISSUE THREAD

**Issue by sarahjstacey15** [ZipArchive/ZipArchive#421] opened 2017-11-08 16:55 UTC
I'm currently working on a project which requires me to unzip multiple folder levels, however once it's unzipped the first level of folders it throws an error (which is nil) and I have to call it again. The only round this at the moment is to set "preserveAttributes" as true and keep recalling it until it's successful, is there a better way to do this? 

`SSZipArchive.unzipFile(atPath: path, toDestination: destination, preserveAttributes: true, overwrite: false, nestedZipLevel: 0, password: password, error: &zipError, delegate: self, progressHandler: nil, completionHandler: {path, succeeded, error -> Void in
if succeeded == true {
//Do stuff here
}
else {
//recall unzip func
}
`

Sample folder structure, where it's not reading "Level 2 B" unless recalled: 

- Level 1 A
     - Level 2 A
     - Level 2 B 
     - Level 2 C
- Level 2 B
     - Level 2 A
     - Level 2 B 
     - Level 2 C

**Comment by Coeur** [comment] 2017-11-09 00:59
Can you provide a sample zip with the issue?
It's the first time I hear about a need of retry, or that a retry would give different outcome than first try.

**Comment by sarahjstacey15** [comment] 2017-11-09 16:36
Due to the content of the files no, it is quite a large file about 65 MB with images and HTML content, it can successfully unzip it I just wondered if there were any known work arounds.

**Comment by Coeur** [comment] 2017-11-10 02:11
You know, some people already shared with me in the past some 3 GB big archives for debuggging. ;)

But there is no known issue of partial unzipping and a need of retry, so there is no question of "work around".

* Be specific if it's iOS or macOS, and which version/filesystem
* Try to remove files from your zip files until the problem is minimal in order to make an MVCE.

We'll certainly find a solution as soon as we can reproduce the issue.

**Comment by sarahjstacey15** [comment] 2017-11-10 09:33
I've tested it on a similar file structure with smaller files and that seems to work so I think it's more the size of the zip, sorry should have stated I'm using iOS and I'm downloading the zip so can't remove files from my end, it is working but does need a re-call.

**Comment by sarahjstacey15** [comment] 2017-11-10 15:56
Done a little more digging and it looks like its failing at the same points each time, but the file is successfully downloading. 

`readBytes = unzReadCurrentFile(zip, buffer, 4096);
                        if (readBytes < 0) {
                            // Let's assume error Z_DATA_ERROR is caused by an invalid password
                            // Let's assume other errors are caused by Content Not Readable
                            success = NO;
                        }`

Here if I log the readBytes is -5 but strangely the file is successfully read next time it is run, when I also log the strPath it looks like its on jpg images which are quite frequent so theres no issue there.

**Comment by Coeur** [comment] 2018-08-26 14:48
Closing, because this issue is lacking a sample or a way to reproduce it.

**Closed by Coeur** 2018-08-26 14:48 UTC
Labels: needs-reproduction
