### ISSUE TITLE
Unable to decrypt files with Carthage library

### ISSUE THREAD

**Issue by hooby3dfx** [ZipArchive/ZipArchive#559] opened 2020-02-27 01:56 UTC
I am trying to use ZipArchive 2.2.2 (downloaded via Carthage) on both macOS and iOS, and have not been able to decrypt a few example files made with other programs.
Attached are 2 sample example files that I am not able to decrypt:
- test7z.zip (created with 7zip on Windows, using AES-256)
- testcsharp.zip (created using SharpZipLib on Windows, using AES-128)

The password for both files is "PositionDescribeMexico" and contained within is one small text file. 

I am able to open/extract the files using 7zip and PKZIP on Windows, and Keka on macOS. 

I made basic changes to the example ZipArchive program to do this testing, using the attached files.

[test7z.zip](https://github.com/ZipArchive/ZipArchive/files/4259075/test7z.zip)
[testcsharp.zip](https://github.com/ZipArchive/ZipArchive/files/4259076/testcsharp.zip)

Edit 1: I just built minizip from source and ran the minizip_cmd, which IS able to decrypt/extract both files. 

Edit 2: FML, the issue on Mac was due to entitlements and running in a sandbox so it couldn't read my file. (I was able to debug by using Cocoapods with full source.) Knowing that the library does work, I will now dig deeper into what the issue is on iOS...

**Comment by willson-chen** [comment] 2020-02-27 03:38
Thanks for your update! :)

**Comment by hooby3dfx** [comment] 2020-02-27 03:42
The plot thickens a bit; on Mac I am still not able to perform the decryption when using the library from Carthage, but I am able to when running the Cocoapods version.
Is it possible that the Carthage build has a problem?

**Comment by hooby3dfx** [comment] 2020-02-27 14:56
I confirmed that on iOS with the Carthage v2.2.2 I am able to unzip non-password protected zip files, but it is failing on the encrypted ones. 
I am however able to call SSZipArchive.isPasswordValidForArchive and get the expected results.

**Comment by hooby3dfx** [comment] 2020-02-28 14:11
OK - After much trial and error, I have determined that I can directly use the SSZipArchive.framework from Cocoapods in place of the ZipArchive.framework from Carthage, and successfully decrypt on iOS.

I strongly suspect there is something wrong with the Carthage binary. 

Note that I am running this on iOS 13 and building with Xcode 11.

**Comment by willson-chen** [comment] 2020-03-02 08:57
Hi @hooby3dfx ,today I used the ZipArchive.framework generated by Carthage on mac, and tested the two zip archives you provided with the simple demo below. Pass in the password you provided, and both of them were successfully decompressed.
```
#import <Foundation/Foundation.h>
#import "SSZipArchive.h"

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        // insert code here...
        NSLog(@"Hello, World!");
        
        NSString *zipPath_test7z =   @"/Users/wilson/workspace/TEST/test7z.zip";
        NSString *unzipPath_test7z = @"/Users/wilson/workspace/TEST/test7z";
        
        BOOL success = [SSZipArchive unzipFileAtPath:zipPath_test7z
                                       toDestination:unzipPath_test7z
                                  preserveAttributes:YES
                                           overwrite:YES
                                      nestedZipLevel:0
                                            password:@"PositionDescribeMexico"
                                               error:nil
                                            delegate:nil
                                     progressHandler:nil
                                   completionHandler:nil];
        if(success)
        {
            NSLog(@"ok-test7z!");
        }
        else{
            NSLog(@"fail-test7z!");
        }
        
        
        NSString *zipPath_testcsharp =   @"/Users/wilson/workspace/TEST/testcsharp.zip";
        NSString *unzipPath_testcsharp = @"/Users/wilson/workspace/TEST/testcsharp";
        
        BOOL success1 = [SSZipArchive unzipFileAtPath:zipPath_testcsharp
                                       toDestination:unzipPath_testcsharp
                                  preserveAttributes:YES
                                           overwrite:YES
                                      nestedZipLevel:0
                                            password:@"PositionDescribeMexico"
                                               error:nil
                                            delegate:nil
                                     progressHandler:nil
                                   completionHandler:nil];
        if(success1)
        {
            NSLog(@"ok-testsharp!");
        }
        else{
            NSLog(@"fail-testsharp!");
        }
        
    }
    return 0;
}
```
zipArchive version : 2.2.2
Xcode version : 11.3

Maybe you can try again using the demo above.

**Comment by nmoinvaz** [comment] 2020-03-02 14:55
Decompress using a third party utility and it will probably fail.

**Comment by willson-chen** [comment] 2020-03-03 00:44
> Decompress using a third party utility and it will probably fail.

Hi, @nmoinvaz . Could you please offer more information about this issue?

**Comment by hooby3dfx** [comment] 2020-03-03 04:23
@willson-chen can you please to reproduce but running on iOS?

I just reproduced this using the Example project SwiftExampleCarthage_iOS target. 
I put testcsharp.zip into the "Sample Data" folder, and made a small modification to this function:


```
    @IBAction func unzipPressed(_: UIButton) {
//        guard let zipPath = self.zipPath else {
//            return
//        }

        guard let unzipPath = tempUnzipPath() else {
            return
        }
        let zipPath = Bundle.main.bundleURL.appendingPathComponent("Sample Data").appendingPathComponent("testcsharp.zip").path
        print("Zip path:", zipPath)
        print("Unzip path:", unzipPath)
        
        let pwSuccess: Bool = SSZipArchive.isPasswordValidForArchive(atPath: zipPath, password: "PositionDescribeMexico", error: nil)
        if(pwSuccess){
            print("pwSuccess")
        }
        
        let password = passwordField.text ?? ""
        let success: Bool = SSZipArchive.unzipFile(atPath: zipPath,
                                                   toDestination: unzipPath,
                                                   preserveAttributes: true,
                                                   overwrite: true,
                                                   nestedZipLevel: 1,
                                                   password: !password.isEmpty ? password : nil,
                                                   error: nil,
                                                   delegate: nil,
                                                   progressHandler: nil,
                                                   completionHandler: nil)
        if success != false {
            print("Success unzip")
            info.text = "Success unzip"
        } else {
            print("No success unzip")
            info.text = "No success unzip"
            return
        }

        var items: [String]
        do {
            items = try FileManager.default.contentsOfDirectory(atPath: unzipPath)
        } catch {
            return
        }

        for (index, item) in items.enumerated() {
            switch index {
            case 0:
                file1.text = item
            case 1:
                file2.text = item
            case 2:
                file3.text = item
            default:
                print("Went beyond index of assumed files")
            }
        }

        unzipButton.isEnabled = false
    }

```

**Comment by willson-chen** [comment] 2020-03-03 07:49
> I just reproduced this using the Example project SwiftExampleCarthage_iOS target.
> I put testcsharp.zip into the "Sample Data" folder, and made a small modification to the below function.
> I get the same results on the simulator and real device.
> Note that SSZipArchive.isPasswordValidForArchive returns true, indicating that the file is readable and that check work.

@hooby3dfx According to the operation you said, my project can also be decompressed normally, and the decompressed is a 212-byte data.test file.


What will be displayed on the simulator? Unzip success or failure? What does the console show? If the decompression is successful, you can enter the Unzip path to view the data.test file through the terminal.

**Comment by hooby3dfx** [comment] 2020-03-03 12:47
Terminal output:
```
Sample path: /Users/bbarnes/Library/Developer/CoreSimulator/Devices/D5C25E21-305E-45D3-8DCC-BCE59396761E/data/Containers/Bundle/Application/D138E8D0-1587-4333-B80D-3F884BEADB1A/SwiftExampleCarthage.app/Sample Data
Zip path: /Users/bbarnes/Library/Developer/CoreSimulator/Devices/D5C25E21-305E-45D3-8DCC-BCE59396761E/data/Containers/Data/Application/1A10C8B1-4B1B-4D2D-B0C6-11E43F13A81F/Library/Caches/D5BA3FB1-98CC-4388-BF86-A1D4709BC3A3.zip
Success zip
Zip path: /Users/bbarnes/Library/Developer/CoreSimulator/Devices/D5C25E21-305E-45D3-8DCC-BCE59396761E/data/Containers/Bundle/Application/D138E8D0-1587-4333-B80D-3F884BEADB1A/SwiftExampleCarthage.app/Sample Data/testcsharp.zip
Unzip path: /Users/bbarnes/Library/Developer/CoreSimulator/Devices/D5C25E21-305E-45D3-8DCC-BCE59396761E/data/Containers/Data/Application/1A10C8B1-4B1B-4D2D-B0C6-11E43F13A81F/Library/Caches/5EA6E595-12A1-4CA9-8962-C2048F6CA859
pwSuccess
No success unzip
```
When clicking "unzip sample data" the app UI also will say "No success unzip".

**Comment by hooby3dfx** [comment] 2020-03-03 13:04
Here are the precise steps I can follow to reproduce the issue:

1. Download ZipArchive-master from GitHub
2. cd into the Example dir
3. Run carthage update
```
bbarnes@PC0012953 Example % carthage update
*** Fetching ZipArchive
*** Checking out ZipArchive at "v2.2.2"
*** xcodebuild output can be found in /var/folders/40/wy2cz3016djgn1kmgf7dz0s40000gp/T/carthage-xcodebuild.GtckSG.log
*** Downloading ZipArchive.framework binary at "v2.2.2"
```
4. On a Mac running OS 10.15.3, Xcode 11.3.1, open Example/ZipArchiveExample.xcodeproj
5. Edit SwiftExample/ViewController.swift with the above changed unzipPressed method
6. Copy the above attached “testcsharp.zip” file into the Sample Data folder
7. Change the target to SwiftExampleCarthage_iOS
8. Run the app on a simulator (iPhone 11 Pro Max)
9. Press zip, and then press unzip 
10. The unzip will not succeed - this is the issue

**Comment by silverhammermba** [comment] 2020-03-03 14:59
I can reproduce the same issue with an iPhone 6s running 13.31.

Built SwiftExample_iOS: unzipping testcsharp.zip succeeds
Built SwiftExampleCarthage_iOS: unzipping testcsharp.zip fails

Also confirmed that SSZipArchive.isPasswordValidForArchive returns true even when unzipping fails. I am also not getting any error (tried both the error pointer and completion handler).

Something is wrong with the carthage version of the example.

**Comment by silverhammermba** [comment] 2020-03-03 15:13
This seems to be related to #547. Downgrading to version 2.1.4 with Carthage resolves the issue

**Comment by willson-chen** [comment] 2020-03-04 07:09
> Here are the precise steps I can follow to reproduce the issue:
> 
> 1. Download ZipArchive-master from GitHub
> 2. cd into the Example dir
> 3. Run carthage update
> 
> ```
> bbarnes@PC0012953 Example % carthage update
> *** Fetching ZipArchive
> *** Checking out ZipArchive at "v2.2.2"
> *** xcodebuild output can be found in /var/folders/40/wy2cz3016djgn1kmgf7dz0s40000gp/T/carthage-xcodebuild.GtckSG.log
> *** Downloading ZipArchive.framework binary at "v2.2.2"
> ```
> 
> 1. On a Mac running OS 10.15.3, Xcode 11.3.1, open Example/ZipArchiveExample.xcodeproj
> 2. Edit SwiftExample/ViewController.swift with the above changed unzipPressed method
> 3. Copy the above attached “testcsharp.zip” file into the Sample Data folder
> 4. Change the target to SwiftExampleCarthage_iOS
> 5. Run the app on a simulator (iPhone 11 Pro Max)
> 6. Press zip, and then press unzip
> 7. The unzip will not succeed - this is the issue

Can you download ZipArchive.framework  directly from https://github.com/ZipArchive/ZipArchive/releases/download/v2.2.2/ZipArchive.framework.zip? 
Drag ZipArchive.framework from the downloaded ios folder to your target project and replace your original ZipArchive.framework,then see if you can unzip successfully?

**Comment by silverhammermba** [comment] 2020-03-05 14:33
@willson-chen That download also fails to unzip it.

**Comment by willson-chen** [comment] 2020-03-11 12:03
I found the problem results from the released [ZipArchive.framework.zip](https://github.com/ZipArchive/ZipArchive/releases/download/v2.2.2/ZipArchive.framework.zip) of v2.2.2.

I follow the instructions in [Release-Instructions.md](https://github.com/ZipArchive/ZipArchive/blob/master/Release-Instructions.md) to create a Carthage framework archive with commit `582949e`, which is also tagged as `v2.2.2`, and it works. But when I create it with commit `97956a9`, which is ahead of `582949e`. and it fails with same error.

So I think maybe the release ZipArchive.framework.zip in v2.2.2 was generated from wrong commit. And we need a new release to correct this error.

**Comment by Coeur** [comment] 2020-03-11 12:31
Interesting. I'm quite sorry if I built an incorrect attachment last year. Let me work on making a new release.

**Comment by hooby3dfx** [comment] 2020-03-18 15:47
Thank you all for helping determine the cause of this issue!
@Coeur I hope all is well - do you have an ETA for making the corrected release?

**Comment by willson-chen** [comment] 2020-04-15 09:17
> Thank you all for helping determine the cause of this issue!
> @Coeur I hope all is well - do you have an ETA for making the corrected release?

@hooby3dfx Thanks for your report. I have make a new release today, and use it unzip your file `testcsharp.zip` successfully.

> Also, out of curiosity, why does there need to be a binary provided as part of the Carthage release?

Maybe from next version we will not release Carthage binary.

**Comment by hooby3dfx** [comment] 2020-04-17 01:23
@willson-chen where is the new release? The releases page still just has 2.2.2.
https://github.com/ZipArchive/ZipArchive/releases
Was 2.2.2 just rebuilt? Or should I wait for a 2.2.3?

**Comment by willson-chen** [comment] 2020-04-17 01:37
I rebuilt the Cathage package and replaced the old one. :)

**Comment by willson-chen** [comment] 2020-04-23 08:20
Carthage binary has been updated, I will close this issue first.

**Closed by willson-chen** 2020-04-23 08:20 UTC
Labels: needs-reproduction
